### ISSUE TITLE
Is linting possible?

### ISSUE THREAD

**Issue by dracan** [carlsmedstad/vim-bicep#1]
Hi! Thank for this plugin - very useful having syntax highlighting in my Bicep files 🙂

I have no idea what's involved with lining - so this might be a silly question - but when vscode gives very powerful linting functionality when editing Bicep files. Is this even possible with Vim?

**Comment by carlsmedstad** [comment]
Hey!

Glad you find it as useful as I do! :slightly_smiling_face:

You have great timing, I just added a configuration for Bicep in the lint engine [ALE](https://github.com/dense-analysis/ale). If you install that, messages should pop up in your editor out of the box as long as you have `bicep` installed. I messed it up a bit so it currently shows all module imports as errors, but that will be fixed when this is merged: https://github.com/dense-analysis/ale/pull/4311.

**Comment by dracan** [comment]
Magic! That works! ❤

I haven't used it properly yet - it does seem to be showing warnings for bicep module references where the reference definitely exists on the file system - but that's probably me not fully reading the docs yet :)

Eg...

![image](https://user-images.githubusercontent.com/567988/191481386-3dc2a4d1-36fe-498b-8756-61bd2ef17389.png)

**Comment by carlsmedstad** [comment]
That will be fixed by the PR I linked above :)

Feel free to give it a thumbs up!

**Comment by dracan** [comment]
Ah sorry! I totally misread what you meant above! 🤦‍♂️
Added both 👍 and ❤️ ! :)

**Comment by dracan** [comment]
Another instance where I feel Github needs this...
https://twitter.com/dracan/status/1570363060967346177
:)
